local M = {}

M.url = "https://github.com/pwntester/octo.nvim"

function M.get()
	return {
		-- colors
		OctoGrey = { fg = C.bgbase },
		OctoBlue = { fg = C.coral },
		OctoGreen = { fg = C.sage },
		OctoRed = { fg = C.ember },
		OctoPurple = { fg = C.mauve },
		OctoYellow = { fg = C.honey },
		-- highlight groups
		OctoDirty = { link = "ErrorMsg" },
		OctoIssueTitle = { link = "PreProc" },
		OctoIssueId = { link = "Question" },
		OctoEmpty = { link = "Comment" },
		OctoFloat = { link = "NormalNC" },
		OctoDate = { link = "Comment" },
		OctoSymbol = { link = "Comment" },
		OctoTimelineItemHeading = { link = "Comment" },
		OctoDetailsLabel = { link = "Title" },
		OctoMissingDetails = { link = "Comment" },
		OctoDetailsValue = { link = "Identifier" },
		OctoDiffHunkPosition = { link = "NormalFloat" },
		OctoCommentLine = { link = "TabLineSel" },
		OctoViewer = { fg = C.bgbase, bg = C.coral },
		OctoBubble = { fg = C.blush, bg = C.bgbase },
		OctoBubbleGrey = { fg = C.blush, bg = C.bgbase },
		OctoBubbleDelimiterGrey = { fg = C.bgbase },
		OctoBubbleGreen = { fg = C.bgbase, bg = C.sage },
		OctoBubbleDelimiterGreen = { fg = C.sage },
		OctoBubbleBlue = { fg = C.bgbase, bg = C.mist },
		OctoBubbleDelimiterBlue = { fg = C.mist },
		OctoBubbleYellow = { fg = C.bgbase, bg = C.honey },
		OctoBubbleDelimiterYellow = { fg = C.honey },
		OctoBubbleRed = { fg = C.bgbase, bg = C.ember },
		OctoBubbleDelimiterRed = { fg = C.ember },
		OctoBubblePurple = { fg = C.bgbase, bg = C.mauve },
		OctoBubbleDelimiterPurple = { fg = C.mauve },
		OctoUser = { link = "OctoBubble" },
		OctoUserViewer = { link = "OctoViewer" },
		OctoReaction = { link = "OctoBubble" },
		OctoReactionViewer = { link = "OctoViewer" },
		OctoPassingTest = { link = "OctoGreen" },
		OctoFailingTest = { link = "OctoRed" },
		OctoPullAdditions = { link = "OctoGreen" },
		OctoPullDeletions = { link = "OctoRed" },
		OctoPullModifications = { fg = C.coral },
		OctoStateOpen = { fg = C.sage, bg = C.bgbase },
		OctoStateOpenFloat = { fg = C.sage, bg = C.bgbase },
		OctoStateClosed = { fg = C.ember, bg = C.bgbase },
		OctoStateClosedFloat = { fg = C.ember, bg = C.bgbase },
		OctoStateMerged = { fg = C.mauve, bg = C.bgbase },
		OctoStateMergedFloat = { fg = C.mauve, bg = C.bgbase },
		OctoStatePending = { fg = C.coral, bg = C.bgbase },
		OctoStatePendingFloat = { fg = C.coral, bg = C.bgbase },
		OctoStateApproved = { link = "OctoStateOpen" },
		OctoStateApprovedFloat = { link = "OctoStateOpen" },
		OctoStateChangesRequested = { fg = C.ember, bg = C.bgbase },
		OctoStateChangesRequestedFloat = { fg = C.ember, bg = C.bgbase },
		OctoStateCommented = { link = "Normal" },
		OctoStateCommentedFloat = { link = "Normal" },
		OctoStateDismissed = { link = "OctoStateClosed" },
		OctoStateDismissedFloat = { link = "OctoStateClosed" },
		OctoStateSubmittedBubble = { link = "OctoBubbleGreen" },
		OctoFilePanelCounter = { fg = C.coral, style = { "bold" } },
		OctoFilePanelTitle = { fg = C.coral, style = { "bold" } },
		OctoFilePanelFileName = {},
		OctoNormalFront = { fg = C.blush },
		OctoYellowFloat = { fg = C.honey, bg = C.bgbase },
		OctoPurpleFloat = { fg = C.mauve, bg = C.bgbase },
		OctoRedFloat = { fg = C.ember, bg = C.bgbase },
		OctoGreenFloat = { fg = C.sage, bg = C.bgbase },
		OctoGreyFloat = { fg = C.blush, bg = C.bgbase },
		OctoBlueFloat = { fg = C.coral, bg = C.bgbase },
		OctoReviewDiffAddText = { bg = U.darken(C.sage, 0.30, C.bgbase) },
		OctoReviewDiffDeleteText = { bg = U.darken(C.ember, 0.30, C.bgbase) },
	}
end

return M

